spring:
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: victoryagraz@gmail.com
    password: rkgc icmt mdrv akjo
    protocol: smtp
    tls: true
    properties:
      registration-text: "Welcome {0}, follow the link below to finish your registration: "
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com



  application:
    name: Bookshop
    security:
      jwtSecret: "===========++++++++++====================================Bookshop=======+++++++=============================================="
      jwtExpirationMs: 6400000


  datasource:
    url: jdbc:postgresql://localhost:5432/BookshopDB
    username: vveselkova
    password: password
    driverClassName: org.postgresql.Driver

server:
  port: 8081